version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql_exam_generator
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - java_exam_generator:/var/lib/mysql

volumes:
  java_exam_generator: